{
 "title": "Monitoring: Citibike Trip Prediction",
 "time": { "from": "2024-12-31T23:00:00.000Z", "to": "2025-01-04T22:59:59.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM citibike_metrics WHERE $__timeFilter(\"timestamp\") ORDER BY \"timestamp\" "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", share_missing_values AS \"value\" FROM citibike_metrics WHERE $__timeFilter(\"timestamp\") ORDER BY \"timestamp\" ASC "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", num_drifted_columns AS \"value\" FROM citibike_metrics WHERE $__timeFilter(\"timestamp\") ORDER BY \"timestamp\" ASC "
    }
   ]
  }
 ]
}